# Note! This role is dependent on the role: 'lvm_volume_group'

- name: Create a thin lvm pool for storage of Docker config and volumes (tp_docker)
  community.general.lvol:
    vg: vg_docker
    thinpool: tp_docker
    size: 90%VG
- name: Create a thin lvm volume for storage of Docker config and volumes (tlv_docker)
  community.general.lvol:
    vg: vg_docker
    lv: tlv_docker
    thinpool: tp_docker
    size: 90%VG
- name: Format the thin volume for docker data with xfs
  community.general.filesystem:
    fstype: xfs
    dev: /dev/vg_docker/tlv_docker
    opts: -i size=512
- name: Create export mount point /export/docker
  file:
    path: /export/docker
    state: directory
    owner: root
    group: root
    mode: 0775
#    recurse: yes
- name: Mount thin volume tlv_docker_volume at /export/docker
  ansible.posix.mount:
    src: /dev/vg_docker/tlv_docker
    fstype: xfs
    path: /export/docker
    state: mounted
