---
# tasks file for biocachebackend
- name: Ensure configuration and script directories
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - etc
    - etc/biocachebackend
    - etc/biocachebackend/env
    - etc/biocachebackend/config
    - usr/biocachebackend
    - usr/biocachebackend/bin
  tags:
    - app_directory

- name: Ensure write access for docker group
  file:
    path: "{{ docker_ctx | default('/docker') }}/{{item}}"
    mode: 0775
    group: docker
    recurse: yes
    state: directory
  with_items:
    - etc/biocachebackend
  tags:
    - write_access

- name: Install "envbiocachebackend.template"
  copy:
    src: etc/envbiocachebackend.template
    dest: "{{ docker_ctx }}/etc/biocachebackend/env/envbiocachebackend.template"
    mode: 0644
  tags:
    - env_template

- name: Install "docker-compose.yml"
  template:
    src: etc/docker-compose.yml
    dest: "{{ docker_ctx | default('/docker') }}/etc/biocachebackend/docker-compose.yml"
    owner: root
    group: root
    mode: 0644
  tags:
    - docker_compose

- name: Install biocache configuration file
  template:
    src: etc/config/biocache-config.properties
    dest: "{{ docker_ctx | default('/docker') }}/etc/biocachebackend/config/biocache-config.properties"
    mode: 0644
  tags:
    - app_config

- name: Install blacklisted Media URL file
  template:
    src: etc/config/blacklistMediaUrls.txt
    dest: "{{ docker_ctx | default('/docker') }}/etc/biocachebackend/config/blacklistMediaUrls.txt"
    mode: 0644
  tags:
    - app_config

- name: Install "application.cfg"
  template:
    src: etc/application.cfg
    dest: "{{ docker_ctx | default('/docker') }}/etc/biocachebackend/application.cfg"
    mode: 0644
  tags:
    - application_cfg
